--- 
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install Nginx and Git
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - git
  become: yes

- name: Clone application repository from GitHub
  git:
    repo: "{{ git_repo }}"
    dest: "{{ nginx_root }}"
    version: "{{ git_version }}"
  become: yes

- name: Configure Nginx using Jinja2 template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ app_name }}
  notify: Restart Nginx
  become: yes

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/{{ app_name }}
    state: link
  become: yes

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes
